config/routes.rb
Rails.application.routes.draw do

  resources :products do

    collection do
      get :stats
    end

    member do
      get :stat
    end
  end

  resources :users, only: [:create]
  resources :orders, only: [:index, :new, :create, :destroy]
  resources :reviews, only: [:create]

  get 'register' => 'users#new', as: 'register'

  get  'login'  => 'sessions#new', as: 'login'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy', as: 'logout'

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  before_save :set_quantity

  def set_quantity
    quantity = 1 if quantity == 0
  end

  # def set_user(user_id)
  #   user_id = user_id
  # end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  has_many :orders
  has_many :buyers, through: :orders, source: :user

  has_many :reviews

  validates :price, numericality: true
  validates_presence_of :name, :price

  scope :cheap,     -> { where('price < 100') }
  scope :expensive, -> { where('price > 100') }
  scope :on_stock,  -> { where(stock: true) }

  def display_stock
    stock ? 'Da' : 'Ne'
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :orders
  has_many :products, through: :orders, source: :product

  has_many :reviews, dependent: :destroy

  validates_presence_of :username, :email

  def check_email
    # to implement :)
  end

  def admin?
    role == 1
  end

  # scope :with_email, ->(email){ where("email = ?", email) }
  # scope :with_username, ->(username){ where("username = ?", username) }
  # scope :with_email_and_username, ->(email, username){ with_email(email).with_username(username).first }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in_user
    # @current_user ||= User.find(session[:user]) if session[:user]
    @current_user ||= find_user
  end

  helper_method :logged_in_user

  protected

    def authorize
      redirect_to login_path unless logged_in_user
    end

    def find_user
      if session[:user]
        User.find(session[:user])
      elsif cookies[:user]
        User.find(cookies[:user])
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authorize

  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authorize

  def index
    if params[:user_id]
      @orders = Order.where(user_id: params[:user_id])
    elsif params[:product_id]
      @orders = Order.where(product_id: params[:product_id])
    else
      @orders = Order.all
    end
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    # @order.user_id = logged_in_user.id
    @order.user = logged_in_user

    if @order.save
      redirect_to orders_path
    else
      render :new
    end
  end

  def destroy
    Order.destroy(params[:id])
    redirect_to orders_path
  end

  private

    def order_params
      params.require(:order).permit(:product_id, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authorize

  def index
    @products_count          = Product.count
    @cheap_products_on_stock = Product.cheap.on_stock

    if params[:sort]
      @products = Product.order(price: :desc)
    else
      @products = Product.all
    end

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @products }
      format.xml { render xml: @products }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to(products_path())
    else
      render :new
    end
  end

  def show
    product_id = params[:id]
    @product = Product.find(product_id)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    product_name = @product.name
    @product.destroy
    flash[:notice] = "Product with name: #{product_name} is successfully deleted :)"
    redirect_to products_path
  end

  def stats
    @total_products = Product.count
    @products_on_stock = Product.where(stock: true).count
  end

  def stat
    product = Product.find(params[:id])
    @product_buyers = product.buyers.count
  end

  private

    def product_params
      params.require(:product).permit(:name, :price, :description, :category_id, :stock)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize

  def create
    @review = Review.new(review_params)
    @review.user = logged_in_user

    @review.save

    @reviews = Review.where("product_id = ?", params[:product_id]).order(created_at: :asc)

    #binding.pry

    respond_to do |format|
      format.js
    end
  end

  private

    def review_params
      params.permit(:content, :product_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #test = "hello debugger"
    #binding.pry
    # @user = User.find(2)
    # @user = User.find_by(email: params[:email])
    # @user = User.find_by_email(params[:email])
    # @user = User.where(email: params[:email]).first
    # @user = User.where("email = ?", params[:email]).first
    # @user = User.where("email = ? AND username = ?", params[:email], params[:username]).first
    # @user = User.where("email = ?", params[:email]).where("username = ?", params[:username]).first
    # @user = User.with_email(params[:email]).with_username(params[:username]).first
    # @user = User.with_email_and_username(params[:email], params[:username])

    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      if params[:remember_me]
        cookies[:user] = { value: @user.id, expires: 1.day.from_now }
      else
        session[:user] = @user.id
      end

      flash[:notice] = 'User authenticated :)'
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password :'("
      redirect_to login_path
    end
  end

  def destroy
    if session[:user]
      session[:user] = nil
    else
      cookies.delete(:user)
    end

    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorize, except: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'User created successfully :)'
      redirect_to root_path
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def order_belongs_to_logged_in_user?(logged_in_user, orders_user)
    # return true if logged_in_user == orders_user
    logged_in_user == orders_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to home page</h1>
<br/>

<%= link_to 'Products', products_path %> |
<%= link_to 'Create product', new_product_path %>
<%= link_to 'Go to shop', new_order_path %>

<% unless flash[:notice].nil? %>
  <h2><%= flash[:notice] %></h2>
<% end %>

<% unless session[:user].nil? %>
  <%= link_to "Logout", logout_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header" style="margin-bottom: 50px;">
  <% if logged_in_user %>
    <%= logged_in_user.username %> |
    <%= link_to 'Logout', logout_path %>
  <% else %>


    <%= link_to login_path do %>
      <%= image_tag 'login-icon.png', size: '24x24' %>
    <% end %>&nbsp;&nbsp;

    <%= link_to 'Register', register_path %>
  <% end %>
</div>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Orders</h1>
    <br/>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th>Created at</th>
          <th>Product name</th>
          <th>Buyer name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.id %></td>
            <td><%= I18n.localize(order.created_at, format: "%d/%m/%Y") %></td>
            <td><%= link_to order.product.name, orders_path(product_id: order.product.id) %></td>
            <td><%= link_to order.user.username, orders_path(user_id: order.user.id) %></td>
            <td>
            <% if order_belongs_to_logged_in_user?(logged_in_user, order.user) %>
              <%= link_to 'Delete', order_path(order.id), method: :delete %>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Create new order</h2>

    <%= form_for(@order) do |form| %>

      <div class="form-group">
        <%= form.label :quantity %>
        <%= form.text_field :quantity, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :product %>
        <%= form.collection_select(:product_id, Product.all, :id, :name) %>
      </div>

      <%= form.submit 'Buy', class: 'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<tr>
  <td>id: <%= product.id %></td>
  <td>name: <%= product.name %></td>
  <td>price: <%= product.price %></td>
  <td><%= link_to 'Details', product_path(product) %> |
  <%= link_to 'Edit', edit_product_path(product) %> |
  <% if logged_in_user.admin? %>
    <%= link_to 'Delete', product_path(product), method: :delete %>
  <% end %>
  </td>
</tr>

app/views/products/_review_form.html.erb
<div class="row" style="margin-bottom: 100px;">
  <div class="col-md-8">
    <%= form_tag(reviews_path, remote: true) do %>

      <div class="form-group">
        <%= label_tag 'Content' %>
        <%= text_area_tag :content, nil, class: 'form-control' %>
      </div>

      <%= hidden_field_tag :product_id, product_id %>

      <%= submit_tag 'Save review', class: 'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h2>Edit product</h2>

<%= form_for(@product) do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %>
  <br/><br/>
  <%= form.label :price %>
  <%= form.text_field :price %>
  <br/><br/>
  <%= form.label :description %>
  <%= form.text_area :description %>
  <br/><br/>
  <%= form.label :category %>
  <%= form.collection_select(:category_id, Category.all, :id, :name) %>
  <br/><br/>
  <%= form.label :stock %>
  <%= form.check_box :stock %>
  <br/><br/>

  <%= form.submit 'Save' %>
<% end %>



<!-- <label for="product[name]">
<input type="text" name="product[name]" value="product 1" /> -->

<!-- <form action="/products/new" method="POST"> -->

app/views/products/index.html.erb
<style>
  .flash {
    height: 40px;
    border: 2px solid red;
    color: red;
    line-height: 40px;
    margin-bottom: 20px;
    width: 400px;
  }
</style>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'shared/page_heading', locals: { text: 'Products page' } %>

    <%= render 'shared/page_heading', text: "Products count #{@products_count}" %>

    <%= render 'shared/test' %>

    <% unless flash[:notice].nil? %>
      <div class="flash"><%= flash[:notice] %></div>
    <% end %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th><%= link_to 'Price', products_path(sort: true), remote: true %></th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody id="products">
        <!-- Products partial templates -->
        <%= render partial: 'product', collection: @products %>
      </tbody>
    </table>

  </div>
</div>

app/views/products/index.js.erb
$('#products').html("<%= j render partial: 'product', collection: @products %>");

app/views/products/new.html.erb
<h2>Create new product</h2>

<%= form_for(@product) do |form| %>

  <% unless @product.errors.empty? %>
    <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <br/>

  <%= form.label :name %>
  <%= form.text_field :name %>
  <br/><br/>
  <%= form.label :price %>
  <%= form.text_field :price, class: 'form-control' %>
  <br/><br/>
  <%= form.label :description %>
  <%= form.text_area :description %>
  <br/><br/>
  <%= form.label :category %>
  <%= form.select :category_id, options_for_select([['Phones', 1], ['Electronics', 2]]) %>
  <br/><br/>
  <%= form.label :stock %>
  <%= form.check_box :stock %>
  <br/><br/>



  <%= form.submit 'Save' %>
<% end %>


<!-- <label for="product[name]"></label>
<input type="text" name="product[name]" /> -->

<!-- <form action="/products/new" method="POST"> -->

app/views/products/show.html.erb
<h1>Product details for product: <%= @product.name %></h1>
<br/>
<h2>id: <%= @product.id %></h2>
<h2>name: <%= @product.name %></h2>
<h2>price: <%= @product.price %></h2>
<br>

<div id="reviews">
  <%= render 'reviews/reviews', reviews: @product.reviews %>
</div>

<%= render 'review_form', product_id: @product.id %>

app/views/products/stat.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/page_heading', text: "Products buyers count #{@product_buyers}" %>
  </div>
</div>

app/views/products/stats.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/page_heading', text: "Total products count #{@total_products}" %>
    <%= render 'shared/page_heading', text: "Products on stock #{@products_on_stock}" %>
  </div>
</div>

app/views/reviews/_reviews.html.erb
<% reviews.each do |review| %>
  <div>
    <p><b><%= review.user.username %></b></p>
    <p><%= review.content %></p>
  </div>
  <hr>
<% end %>

app/views/reviews/create.js.erb
<% if @review.persisted? %>
  $("#reviews").html("<%= escape_javascript(render 'reviews/reviews', reviews: @reviews) %>");

  //alert("Hello it's me :)");
<% else %>
  alert("Nooooooo :'(");
<% end %>

app/views/shared/_page_heading.html.erb
<h1><%= text %></h1>

app/views/shared/_test.html.erb
<h1>fweijfiwoejgw</h1>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Register page</h1>

  <%= form_for(@user, url: users_path) do |f| %>

    <% unless @user.errors.empty? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <%= f.submit 'Register', class: 'btn btn-primary btn-block' %>

  <% end %>
</div>